### ISSUE TITLE
Unable to use the bot

### ISSUE THREAD

**Issue by boiyelove** [arugaz/whatsapp-bot#476]
### Description

```bash
After setup, I tried to run the bot but all I get is an image.
```

### Reproduction steps

```bash
1. Clone the repository & run the app
2. Install dependencies
3. Setup Database and env
4. Run npx... push
5. npm start
```

### Screenshots

![image](https://github.com/arugaz/whatsapp-bot/assets/4135713/f30b0d20-e6bc-4286-8230-8a5aa1061805)

### Whatsapp Version

3.0.0

### OS

Windows

**Comment by arugaz** [comment]
Im gonna fix it today!

**Comment by boiyelove** [comment]
Have you been able to fix it?
Or how can I help?

**Comment by arugaz** [comment]
I have fixed it, u can try

**Comment by boiyelove** [comment]
What's the url to try?
Like localhost:5000 or something

**Comment by boiyelove** [comment]
I tried it just now and it's still the same.
![image](https://github.com/arugaz/whatsapp-bot/assets/4135713/27e85127-7930-480a-a141-f92898006d7c)

Would you be willing to jump on a google meet and walk me through it?

**Comment by arugaz** [comment]
have you rebuild source?

```bash
npm run build
```

**Comment by Cosm1cBug** [comment]
How do i add more commands?

**Comment by arugaz** [comment]
> How do i add more commands?
> 

Please create new issues or on tab disscusions
